# Swagger generated API stub

Micronaut stub


## Overview
This code was generated by the [swagger-codegen-micronaut-generator](https://github.com/franz-see/swagger-codegen-micronaut-generator) project.
By using the [OpenAPI-Spec](https://github.com/swagger-api/swagger-core), you can easily generate an API stub.
This is an example of building API stub interfaces in Java using the Micronaut framework.

The stubs generated can be used in your existing Micronaut application to create controller endpoints
by adding ```@Controller``` classes that implement the interface. Eg:
```java
@Controller
public class PetController implements PetApi {
// implement all PetApi methods
}
```
